//https://github.com/jonlamb-gh/oscc/blob/master/api/include/vehicles/kia_soul_ev.h

pub const ACCELERATOR_OVERRIDE_THRESHOLD: u32 = 185;

pub const STEPS_PER_VOLT: f32 = 819.2;

pub const FAULT_HYSTERESIS: u32 = 100;

pub const TORQUE_DIFFERENCE_OVERRIDE_THRESHOLD: u16 = 1600;

pub const MINIMUM_THROTTLE_COMMAND: f32 = 0.0_f32;
pub const MAXIMUM_THROTTLE_COMMAND: f32 = 1.0_f32;

pub const THROTTLE_SPOOF_LOW_SIGNAL_VOLTAGE_MIN: f32 = 0.30;
pub const THROTTLE_SPOOF_LOW_SIGNAL_VOLTAGE_MAX: f32 = 2.0;

pub const THROTTLE_SPOOF_HIGH_SIGNAL_VOLTAGE_MIN: f32 = 0.70;
pub const THROTTLE_SPOOF_HIGH_SIGNAL_VOLTAGE_MAX: f32 = 4.10;

pub const THROTTLE_SPOOF_LOW_SIGNAL_RANGE_MIN: u16 = 245;
pub const THROTTLE_SPOOF_LOW_SIGNAL_RANGE_MAX: u16 = 1638;

pub const THROTTLE_SPOOF_HIGH_SIGNAL_RANGE_MIN: u16 = 573;
pub const THROTTLE_SPOOF_HIGH_SIGNAL_RANGE_MAX: u16 = 3358;

pub const MINIMUM_TORQUE_COMMAND: f32 = -12.8;
pub const MAXIMUM_TORQUE_COMMAND: f32 = 12.7;

pub const STEERING_SPOOF_LOW_SIGNAL_VOLTAGE_MIN: f32 = 0.80;
pub const STEERING_SPOOF_LOW_SIGNAL_VOLTAGE_MAX: f32 = 4.10;

pub const STEERING_SPOOF_HIGH_SIGNAL_VOLTAGE_MIN: f32 = 0.90;
pub const STEERING_SPOOF_HIGH_SIGNAL_VOLTAGE_MAX: f32 = 4.20;

pub const STEERING_SPOOF_HIGH_SIGNAL_RANGE_MIN: u16 = 738;
pub const STEERING_SPOOF_HIGH_SIGNAL_RANGE_MAX: u16 = 3440;

pub const STEERING_SPOOF_LOW_SIGNAL_RANGE_MIN: u16 = 656;
pub const STEERING_SPOOF_LOW_SIGNAL_RANGE_MAX: u16 = 3358;

pub const TORQUE_SPOOF_LOW_SIGNAL_CALIBRATION_CURVE_SCALE: f32 = 0.135;
pub const TORQUE_SPOOF_LOW_SIGNAL_CALIBRATION_CURVE_OFFSET: f32 = 2.39;

pub const TORQUE_SPOOF_HIGH_SIGNAL_CALIBRATION_CURVE_SCALE: f32 = -0.145;
pub const TORQUE_SPOOF_HIGH_SIGNAL_CALIBRATION_CURVE_OFFSET: f32 = 2.42;

pub const MINIMUM_BRAKE_COMMAND: f32 = 0.0;
pub const MAXIMUM_BRAKE_COMMAND: f32 = 1.0;

pub const BRAKE_SPOOF_LOW_SIGNAL_VOLTAGE_MIN: f32 = 0.333;
pub const BRAKE_SPOOF_LOW_SIGNAL_VOLTAGE_MAX: f32 = 1.12;

pub const BRAKE_SPOOF_HIGH_SIGNAL_VOLTAGE_MIN: f32 = 0.698;
pub const BRAKE_SPOOF_HIGH_SIGNAL_VOLTAGE_MAX: f32 = 2.29;

pub const BRAKE_SPOOF_LOW_SIGNAL_RANGE_MIN: u16 = 273;
pub const BRAKE_SPOOF_LOW_SIGNAL_RANGE_MAX: u16 = 917;

pub const BRAKE_SPOOF_HIGH_SIGNAL_RANGE_MIN: u16 = 572;
pub const BRAKE_SPOOF_HIGH_SIGNAL_RANGE_MAX: u16 = 1875;

pub const BRAKE_PEDAL_OVERRIDE_THRESHOLD: u16 = 130;
pub const BRAKE_LIGHT_SPOOF_LOW_THRESHOLD: u16 = 300;
pub const BRAKE_LIGHT_SPOOF_HIGH_THRESHOLD: u16 = 600;

pub const KIA_SOUL_OBD_STEERING_WHEEL_ANGLE_CAN_ID: u16 = 0x2B0;
pub const KIA_SOUL_OBD_WHEEL_SPEED_CAN_ID: u16 = 0x4B0;
pub const KIA_SOUL_OBD_BRAKE_PRESSURE_CAN_ID: u16 = 0x220;
pub const KIA_SOUL_OBD_THROTTLE_PRESSURE_CAN_ID: u16 = 0x200;
