#!/usr/bin/env bash

set -e

arm-none-eabi-objcopy \
    -O ihex \
    target/thumbv7em-none-eabihf/release/oxcc \
    target/thumbv7em-none-eabihf/release/oxcc.hex

st-flash --format ihex write target/thumbv7em-none-eabihf/release/oxcc.hex

exit 0
